= Getting Started with Nokee Plugins
:jbake-status: published
:jbake-type: manual_chapter
:jbake-tags: user manual, getting started, nokee plugin, gradle
:jbake-description: Learn how to get started with building native projects in Gradle.

Getting started with Nokee plugins is simple and easy.

WARNING: We used to have multiple ways to get started with Nokee plugins.
We recommend using Nokee Version Management plugin over specialized PluginManagement block or individual versions.

Using the <<plugin:nokee-version-management, Nokee Version Management plugin>> is the preferred way to get started.
You will lower your maintenance cost when upgrading to a newer version, both released and snapshots, as well as aligns all the plugin versions together for maximum compatibility.
First, apply the <<plugin:nokee-version-management, Nokee Version Management plugin>> to your settings script using the link:{gradle-user-manual}/plugins.html#sec:plugins_block[plugins DSL block]:

.Apply Nokee Version Management plugin
====
[.multi-language-sample]
=====
.settings.gradle
[source,groovy]
----
plugins {
    id 'dev.nokee.nokee-version-management' version 'latest.version'    // <1>
}
----
=====
[.multi-language-sample]
=====
.settings.gradle.kts
[source,kotlin]
----
plugins {
    id("dev.nokee.nokee-version-management") version("latest.version")  // <1>
}
----
=====
====
<1> The latest status version, `latest.release`, is link:https://docs.gradle.org/7.0/release-notes.html[only supported starting Gradle 7.0].
For older Gradle, please use the link:https://plugins.gradle.org/plugin/dev.nokee.nokee-version-management[latest version available].

NOTE: The Nokee Version Management plugin does not refer to the Nokee version to use.
Instead, the plugin will <<sec:nokee-version-management-sourcing, choose the Nokee version from various location>>.
On the first use, the plugin will <<sec:nokee-version-management-seeding, seed a new Nokee version>> that best match your project.

Second, apply one of <<plugin-references.adoc#,Nokee plugins>> to your build using the link:{gradle-user-manual}/plugins.html#sec:plugins_block[plugins DSL block]:

.Apply Nokee plugin
====
[.multi-language-sample]
=====
.build.gradle
[source,groovy]
----
plugins {
   id 'dev.nokee.jni-library'
}
----
=====
[.multi-language-sample]
=====
.build.gradle.kts
[source,kotlin]
----
plugins {
   id("dev.nokee.jni-library")
}
----
=====
====
