= Getting Started with Nokee Plugins
:jbake-type: manual_chapter
:jbake-tags: user manual, getting started, nokee plugin, gradle
:jbake-description: Learn how to get started with building native projects in Gradle.

Getting started with Nokee plugins is simple and easy.

== Method 1: Using PluginManagement block (preferred)

Using the link:{gradle-user-manual}/plugins.html#sec:plugin_management[Plugin Management block] is the preferred way to get started.
You will lower your maintenance cost when upgrading to a newer version, both released and nightly, as well as aligns all the plugin versions together for maximum compatibility.
First, copy the following `pluginManagement` block to your settings script:

.Configuring Gradle plugin resolution
====
[.multi-language-sample]
=====
.settings.gradle
[source,groovy,subs=attributes+]
----
pluginManagement {
   repositories {
      gradlePluginPortal()
      maven { url = uri('https://repo.nokee.dev/release') }
      maven { url = uri('https://repo.nokee.dev/snapshot') }
   }
   def nokeeVersion = '{jbake-version}'
   resolutionStrategy {
      eachPlugin {
         if (requested.id.id.startsWith('dev.nokee.')) {
            useModule("${requested.id.id}:${requested.id.id}.gradle.plugin:${nokeeVersion}")
         }
      }
   }
}
----
=====
[.multi-language-sample]
=====
.settings.gradle.kts
[source,kotlin,subs=attributes+]
----
pluginManagement {
   repositories {
      gradlePluginPortal()
      maven { url = uri("https://repo.nokee.dev/release") }
      maven { url = uri("https://repo.nokee.dev/snapshot") }
   }
   val nokeeVersion = "{jbake-version}"
   resolutionStrategy {
      eachPlugin {
         if (requested.id.id.startsWith("dev.nokee.")) {
            useModule("${requested.id.id}:${requested.id.id}.gradle.plugin:${nokeeVersion}")
         }
      }
   }
}
----
=====
====

Second, apply one of <<plugin-references.adoc#,Nokee plugins>> to your build using the link:{gradle-user-manual}/plugins.html#sec:plugins_block[plugins DSL block]:

.Apply Nokee plugin
====
[.multi-language-sample]
=====
.build.gradle
[source,groovy]
----
plugins {
   id 'dev.nokee.jni-library'
}
----
=====
[.multi-language-sample]
=====
.build.gradle.kts
[source,kotlin]
----
plugins {
   id("dev.nokee.jni-library")
}
----
=====
====

== Method 2: Using Plugin DSL with version

You can also apply one of <<plugin-references.adoc#,Nokee plugins>> by link:{gradle-user-manual}/plugins.html#sec:plugins_block[pecifying the version inside the plugins block] as shown in the following example.
Because of the link:{gradle-user-manual}/plugins.html#plugins_dsl_limitations[various limitation of the plugin DSL], it is strongly recommended to use the first method.

.Apply Nokee plugin with version
====
[.multi-language-sample]
=====
.build.gradle
[source,groovy,subs=attributes+]
----
plugins {
   id 'dev.nokee.jni-library' version '{jbake-version}'
}
----
=====
[.multi-language-sample]
=====
.build.gradle.kts
[source,kotlin,subs=attributes+]
----
plugins {
   id("dev.nokee.jni-library") version '{jbake-version}'
}
----
=====
====
