= Groovy Gradle Plugin Development Plugin
:jbake-status: published
:jbake-type: reference_chapter
:jbake-tags: user manual, gradle plugin reference, groovy, gradle plugin, gradle, plugin
:jbake-description: Learn what the Groovy Gradle Plugin plugin (i.e. dev.gradleplugins.groovy-gradle-plugin) has to offer for your Gradle build.

Use the Groovy Gradle Plugin development plugin to assist Gradle plugin development implemented in Groovy.
It configures the project to compile Groovy code, adds the Gradle API dependency as well as a compatible Groovy runtime dependency to the `compileOnly` configuration, and performs validation of plugin metadata.
It is a drop-in replacement for the Gradle `java-gradle-plugin` and `groovy` core plugin.

[[sec:groovy-gradle-plugin-usage]]
== Usage

.Applying the Groovy Gradle Plugin Development plugin
====
[.multi-language-sample]
=====
.build.gradle
[source,groovy]
----
plugins {
   id 'dev.gradleplugins.groovy-gradle-plugin' version '1.6.8'
}
----
=====
[.multi-language-sample]
=====
.build.gradle.kts
[source,kotlin]
----
plugins {
   id("dev.gradleplugins.groovy-gradle-plugin") version("1.6.8")
}
----
=====
====

[[sec:groovy-gradle-plugin-extensions]]
== Extensions

The plugin provides the following extensions:

`gradlePluginDevelopment()` on RepositoryHandler::
Adds the Gradle API redistribution repository to the project, e.g. `https://repo.nokee.dev/release`.
Reads the <<gradle-plugin-development.adoc#sec:gradle-dev-redistributed-gradle-api,redistributed Gradle API section>> to learn more.

`gradleApi(version)` on DependencyHandler::
Creates a dependency on the Gradle API of the specified version, i.e. `dev.gradleplugins:gradle-api:2.14.1`.
Reads the <<gradle-plugin-development.adoc#sec:gradle-dev-redistributed-gradle-api,redistributed Gradle API section>> to learn more.

`compatibility` script block on GradlePluginDevelopmentExtension::
Configures the Gradle plugin compatibility for the project, e.g. minimum supported Gradle version.
Reads the <<gradle-plugin-development.adoc#sec:gradle-dev-minimum-gradle-version,minimum Gradle version section>> to learn more.

`groovy` script block on GradlePluginDevelopmentExtension::
Configures the additional Javadoc, Groovydoc and source JARs for the project.
