= Objective-{cpp} Language
:jbake-type: reference_chapter
:jbake-tags: user manual, gradle plugin reference, objective c\+\+, native, gradle
:jbake-description: Learn what the Nokee's Objective-{cpp} language plugin (i.e. dev.nokee.objective-cpp-language) has to offer for your Gradle build.

The Objective-{cpp} Language Plugin provides the tasks, configurations and conventions for compiling Objective-{cpp} source files.
It's an implementation language plugin and works in tandem with plugins providing a runtime and/or entry point.

== Usage

.Applying the Objective-{cpp} Language Plugin
====
[.multi-language-sample]
=====
.build.gradle
[source,groovy]
----
plugins {
   id 'dev.nokee.objective-cpp-language'
}
----
=====
[.multi-language-sample]
=====
.build.gradle.kts
[source,kotlin]
----
plugins {
   id("dev.nokee.objective-cpp-language")
}
----
=====
====

// TODO: Describe runtime plugin and entry point plugin
NOTE: This plugin provides the Objective-{cpp} implementation language capability to a project already providing a runtime and/or entry point, such as the <<jni-library-plugin.adoc#,JNI Library Plugin>>.

== Conventions

The Objective-{cpp} Language Plugin adds conventions for sources, shown below.

=== Project layout

The plugin assumes the project layout shown below.
None of these directories needs to exist or have anything in them.
The compile tasks will compile whatever it finds and ignore anything missing.

`src/main/objcpp`::
Objective-{cpp} source with extension of `.mm`

`src/main/headers`::
Headers - headers needed to compile the library
