[[chapter:plugin-reference]]
= Nokee Plugin Reference
:jbake-type: reference_index
:jbake-tags: user manual, gradle plugin reference, nokee plugin, gradle
:jbake-description: Learn about all the Gradle plugins offered by Nokee.

This page contains links and short descriptions for all the core plugins provided by Nokee.

[[sec:plugin-reference-jvm]]
== JVM Runtimes

<<jni-library-plugin.adoc#,Java Native Interface (JNI) Library>>::
Provides support for building JNI library.

[[sec:plugin-reference-ios]]
== iOS Development

<<objective-c-ios-application-plugin.adoc#,Objective-C iOS Application>>::
Provides support for building Objective-C application for iOS devices.

[[sec:plugin-reference-native-development]]
== Native Development

<<c-application-plugin.adoc#,C Application>>::
Provides support for building C application on Windows, Linux, and macOS.

<<c-library-plugin.adoc#,C Library>>::
Provides support for building C library on Windows, Linux, and macOS.

<<cpp-application-plugin.adoc#,{cpp} Application>>::
Provides support for building {cpp} application on Windows, Linux, and macOS.

<<cpp-library-plugin.adoc#,{cpp} Library>>::
Provides support for building {cpp} library on Windows, Linux, and macOS.

<<objective-c-application-plugin.adoc#,Objective-C Application>>::
Provides support for building Objective-C application on Linux, and macOS.

<<objective-c-library-plugin.adoc#,Objective-C Library>>::
Provides support for building Objective-C library on Linux, and macOS.

<<objective-cpp-application-plugin.adoc#,Objective-{cpp} Application>>::
Provides support for building Objective-{cpp} application on Linux, and macOS.

<<objective-cpp-library-plugin.adoc#,Objective-{cpp} Library>>::
Provides support for building Objective-{cpp} library on Linux, and macOS.

<<swift-application-plugin.adoc#,Swift Application>>::
Provides support for building Swift application on Linux and macOS.

<<swift-library-plugin.adoc#,Swift Library>>::
Provides support for building Swift library on Linux and macOS.

[[sec:plugin-reference-native-languages]]
== Native Languages

<<cpp-language-plugin.adoc#,{cpp} Language>>::
Provides support for compiling {cpp} language.

<<c-language-plugin.adoc#,C Language>>::
Provides support for compiling C language.

<<objective-c-language-plugin.adoc#,Objective-C Language>>::
Provides support for compiling Objective-C language.

<<objective-cpp-language-plugin.adoc#,Objective-{cpp} Language>>::
Provides support for compiling Objective-{cpp} language.

[[sec:plugin-reference-ide]]
== IDE Integration

<<xcode-ide-plugin.adoc#,Xcode IDE>>::
Generates Xcode workspace and project files for the build that can be opened by the IDE.

[[sec:plugin-reference-gradledev]]
== Gradle Plugin Development

<<gradle-plugin-development-plugin.adoc#,Gradle Plugin Development Plugin>>::
Provides additional support for developing Gradle plugin-related projects.

<<java-gradle-plugin-plugin.adoc#,Java Gradle Plugin Development Plugin>>::
Provides support for developing Gradle plugins implemented in Java.

<<groovy-gradle-plugin-plugin.adoc#,Groovy Gradle Plugin Development Plugin>>::
Provides support for developing Gradle plugins implemented in Groovy.

<<gradle-plugin-unit-test-plugin.adoc#,Gradle Plugin Unit Test Plugin>>::
Provides support for unit testing Gradle plugins.

<<gradle-plugin-functional-test-plugin.adoc#,Gradle Plugin Functional Test Plugin>>::
Provides support for functional testing Gradle plugins.
