= Nokee Release Notes
:jbake-type: release_notes
:jbake-tags: {jbake-version}, jvm, jni, objective c, objective cpp
:jbake-description: See what version {jbake-version} of the Gradle Nokee plugins has to offer!

The Nokee team is excited to announce the second release onward to a better native development experience in Gradle.

This release focus on adding <<release-notes.adoc#sec:macos-framework,support for macOS framework>> as well as adding <<release-notes.adoc#sec:objc-objcpp,support for Objective-C and Objective-C++ implementation languages>>.
It extends <<release-notes.adoc#sec:testing-coverage,automated test coverage to macOS, Linux, and Windows>> and adds <<release-notes.adoc#sec:jni-resource-path,configuration for the resource path for the native libraries embedded inside the Java Native Interface (JNI) library>>.

Since the last release, we tried many experiments for the work to come.
You can read all about them in the link:/blog/release-0.2-announcement[announcement blog for this release].

[[sec:getting-started]]
== Getting Started

To use the Nokee plugins in Gradle, simply copy the following code to the settings script of your project, then apply any of the <<manual/plugin-references.adoc#,Nokee plugins>> to your build using the link:{gradle-user-manual}/plugins.html#sec:plugins_block[plugins DSL block]:

.Configuring Gradle plugin resolution
====
[.multi-language-sample]
=====
.settings.gradle
[source,groovy,subs=attributes+]
----
pluginManagement {
   repositories {
      gradlePluginPortal()
      maven {
         url = uri('https://dl.bintray.com/nokeedev/distributions-snapshots')
      }
   }
   def nokeeVersion = '{jbake-version}'
   resolutionStrategy {
      eachPlugin {
         if (requested.id.id.startsWith('dev.nokee.')) {
            useModule("${requested.id.id}:${requested.id.id}.gradle.plugin:${nokeeVersion}")
         }
      }
   }
}
----
=====
[.multi-language-sample]
=====
.settings.gradle.kts
[source,kotlin,subs=attributes+]
----
pluginManagement {
   repositories {
      gradlePluginPortal()
      maven {
         url = uri("https://dl.bintray.com/nokeedev/distributions-snapshots")
      }
   }
   val nokeeVersion = "{jbake-version}"
   resolutionStrategy {
      eachPlugin {
         if (requested.id.id.startsWith("dev.nokee.")) {
            useModule("${requested.id.id}:${requested.id.id}.gradle.plugin:${nokeeVersion}")
         }
      }
   }
}
----
=====
====

[[sec:macos-framework]]
== Framework Support on macOS

The Nokee plugin support link:samples/jni-library-with-framework-dependencies[macOS framework dependencies as normal dependencies].
It is also possible to depend on frameworks within other frameworks (also known as subframework).
For example, `JavaNativeFoundation` is a subframework of `JavaVM` framework and is required for Cocoa development in Java through the JNI runtime.
You can depend on subframework by requesting the link:{gradle-user-manual}/dependency_management_terminology.html#sub:terminology_capability[capability] matching the target subframework.

Because the underlying implementation relies on Gradle core native infrastructure, there are some inherent limitations.
We will work out those limitations in future releases.
The most important limitation is the ordering of the framework against header search paths and libraries to link.
The frameworks should be allowed to interleave with other compiler and linker inputs.
Instead, the command line passed to the compiler and linker group the frameworks.
Also, the files inside a framework don't participate in the up-to-date checking for the compiler and linker tasks.
However, since the framework support is limited to system frameworks, it is unlikely to change between build invocation, causing build issues.
Finally, this release doesn't support dynamic version resolution of frameworks.

[[sec:jni-resource-path]]
== Resource Path Customization

The link:samples/jni-library-with-resource-path[mapping of the native runtime libraries inside the JNI library JAR is customizable per-variant].
It will help with the migration from existing custom JNI support to the Nokee's JNI library support.

[[sec:objc-objcpp]]
== Objective-C and Objective-{cpp} Support

The JNI library plugin now support link:samples/java-objective-c-jni-library[Objective-C] and link:samples/java-objective-cpp-jni-library[Objective-{cpp}] implementation language via <<manual/plugin-references.adoc#sec:native-language-plugins,new language plugins>>.
They work just like the other, C and {cpp}, language plugins.

[[sec:testing-coverage]]
== Plugins Testing Coverage

This release continues improving the testing coverage to prevent unintended breakage in future releases.
Nokee's continuous integration infrastructure covers all three major operating systems (e.g. Windows, macOS and Linux).
Native toolchains and Gradle distribution coverage are still partial.
Improvement will come in the next release.

[[sec:reporting-problems]]
== Reporting Problems
If you find a problem with any of the plugins, please file a bug on https://github.com/nokeedev/gradle-native[GitHub Issues] adhering to our issue guidelines.
If you're not sure you're encountering a bug, please https://discuss.gradle.org/tags/c/help-discuss/14/native[use the Gradle user forum] or the https://app.slack.com/client/TA7ULVA9K/CDDGUSJ7R[[Gradle Community Slack].

Let's build happiness with Gradle, and I'm looking forward to your feedback via https://twitter.com/nokeedev[Twitter] or on https://github.com/nokeedev[GitHub].
