= Nokee Release Notes
:jbake-type: release_notes
:jbake-tags: {jbake-version}, jvm, jni, objective c, objective cpp, c, swift
:jbake-description: See what version {jbake-version} of the Gradle Nokee plugins has to offer!

The Nokee team is pleased to announce an important milestone in native development with Gradle.

[[sec:getting-started]]
== Getting Started

To use the Nokee plugins in Gradle, copy the following code to the settings script of your project, then apply any of the <<manual/plugin-references.adoc#,Nokee plugins>> to your build using the link:{gradle-user-manual}/plugins.html#sec:plugins_block[plugins DSL block]:

.Configuring Gradle plugin resolution
====
[.multi-language-sample]
=====
.settings.gradle
[source,groovy,subs=attributes+]
----
pluginManagement {
   repositories {
      gradlePluginPortal()
      maven { url = uri('https://repo.nokee.dev/release') }
      maven { url = uri('https://repo.nokee.dev/snapshot') }
   }
   def nokeeVersion = '{jbake-version}'
   resolutionStrategy {
      eachPlugin {
         if (requested.id.id.startsWith('dev.nokee.')) {
            useModule("${requested.id.id}:${requested.id.id}.gradle.plugin:${nokeeVersion}")
         }
      }
   }
}
----
=====
[.multi-language-sample]
=====
.settings.gradle.kts
[source,kotlin,subs=attributes+]
----
pluginManagement {
   repositories {
      gradlePluginPortal()
      maven { url = uri("https://repo.nokee.dev/release") }
      maven { url = uri("https://repo.nokee.dev/snapshot") }
   }
   val nokeeVersion = "{jbake-version}"
   resolutionStrategy {
      eachPlugin {
         if (requested.id.id.startsWith("dev.nokee.")) {
            useModule("${requested.id.id}:${requested.id.id}.gradle.plugin:${nokeeVersion}")
         }
      }
   }
}
----
=====
====

// TODO: Deprecate withType from all view
//  For withType(Class).configureEach(...) -> configureEach(Class, Action)
//  For withType(Class).getElements() -> filter(t -> t instanceof Class).map(t -> (List<T>)t)
//  The last one is more complex but we will be rolling out more helper for creating specs

[[sec:reporting-problems]]
== Reporting Problems
If you find a problem with any of the plugins, https://github.com/nokeedev/gradle-native[please open an issue on GitHub].
If you're not sure you're encountering a bug, please https://discuss.gradle.org/tags/c/help-discuss/14/native[use the Gradle user forum] or the https://app.slack.com/client/TA7ULVA9K/CDDGUSJ7R[Gradle Community Slack].

Let's build happiness with Gradle, and looking forward to your feedback via https://twitter.com/nokeedev[Twitter] or on https://github.com/nokeedev[GitHub].
