= {C Application} Custom Source File cherry-picking
:summary: Set custom source file cherry-picking for a {C application}.
:type: sample-chapter
:tags: sample, {application}, sources, native, {C}, gradle
:category: {C}
:description: See how to set the source file cherry-picking of {an application} implemented in {C} using the Gradle Nokee plugins.

NOTE: You can open this sample inside an IDE using the https://www.jetbrains.com/help/idea/gradle.html#gradle_import_project_start[IntelliJ native importer] or https://projects.eclipse.org/projects/tools.buildship[Eclipse Buildship].

Here is a sample where we set the source file cherry-picking {an application} implemented in {C} with no dependencies and minimal configuration.

[source,groovy]
----
plugins {
	id 'dev.nokee.c-application'    // <1>
}

application {
    cSources.setFrom('srcs/main.c', 'srcs/potato/greeter.c') // <2>
    privateHeaders.setFrom(fileTree('incs') { include 'tomato/greeter.h' }) // <3>
    // See note regarding privateHeaders/publicHeaders
}

----
<1> Apply the <<plugin:c-application, C application plugin>>.
<2> Set application sources from  `srcs/main.c` and `srcs/potato/greeter.c` files
<3> Important to set private headers with the *include* pattern using *fileTree* to ensure the proper header search paths.
When a header file is picked by file path alone, the parent directory (enclosing directory) will be selected as one of the header search paths.
+
NOTE: Although users can cherry-pick header files by file path alone,
we recommend using a *fileTree* to cherry-pick the headers.
You can mix *cherry-picking*, *globing* and *generated* sources via appending.


Demonstration below where we see the application builds and runs:

[source,terminal]
----
$ ./gradlew assemble

BUILD SUCCESSFUL
4 actionable tasks: 4 executed

----

