= Minimum Supported Gradle Version
:jbake-status: published
:jbake-summary: Target a different Gradle version than the current running Gradle during plugin development.
:jbake-type: sample_chapter
:jbake-tags: sample, gradle plugin development, gradle
:jbake-category: Gradle Plugin Development
:jbake-description: See how the Nokee team is helping the Gradle community develop better plugin by modelling the minimum Gradle version.
:jbake-permalink: gradle-plugin-development-with-minimum-gradle-version
:jbake-archivebasename: GradlePluginDevelopmentWithMinimumGradleVersion
:jbake-archiveversion: 1.6.8

NOTE: Open this sample in an IDE using https://www.jetbrains.com/help/idea/gradle.html#gradle_import_project_start[IntelliJ native importer], https://projects.eclipse.org/projects/tools.buildship[Eclipse Buildship].

This sample shows how the minimum Gradle version modelling offered by `dev.gradleplugins.java-gradle-plugin` (and `dev.gradleplugins.groovy-gradle-plugin`) can improve your Gradle plugin development.
The plugin only has dependencies on the redistributed Gradle API, <<../../manual/gradle-plugin-development.adoc#sec:gradle-dev-redistributed-gradle-api,see this chapter for more information>>.
The build also has a minimal configuration with a vanilla TestKit test.

====
[.multi-language-sample]
=====
.build.gradle
[source,groovy]
----
include::groovy-dsl/build.gradle[]
----
=====
[.multi-language-sample]
=====
.build.gradle.kts
[source,kotlin]
----
include::kotlin-dsl/build.gradle.kts[]
----
=====
====
<1> See the <<../../manual/gradle-plugin-development.adoc#sec:gradle-dev-testing,Gradle plugin development section on test suites>> in the user manual, and the link:../gradle-plugin-development-with-test-suites[test suites sample].

To build and test the plugin:

[listing.terminal]
----
$ ./gradlew test

BUILD SUCCESSFUL
6 actionable tasks: 6 executed
----

The plugin builds and executes the test as expected.
The important point here is the implicit dependencies:

[listing.terminal]
----
$ ./gradlew dependencies
...
compileClasspath - Compile classpath for source set 'main'.
\--- dev.gradleplugins:gradle-api:5.1
     \--- org.codehaus.groovy:groovy:2.5.4
...
testRuntimeClasspath - Runtime classpath of source set 'test'.
+--- org.spockframework:spock-bom:2.0-groovy-3.0
|    \--- org.spockframework:spock-core:2.0-groovy-3.0 (c)
\--- org.spockframework:spock-core -> 2.0-groovy-3.0
     +--- org.junit:junit-bom:5.7.2
     |    +--- org.junit.platform:junit-platform-engine:1.7.2 (c)
     |    +--- org.junit.platform:junit-platform-testkit:1.7.2 (c)
     |    +--- org.junit.platform:junit-platform-commons:1.7.2 (c)
     |    \--- org.junit.platform:junit-platform-launcher:1.7.2 (c)
     +--- org.codehaus.groovy:groovy:3.0.8
     +--- org.junit.platform:junit-platform-engine -> 1.7.2
     |    +--- org.junit:junit-bom:5.7.2 (*)
     |    +--- org.apiguardian:apiguardian-api:1.1.0
     |    +--- org.opentest4j:opentest4j:1.2.0
     |    \--- org.junit.platform:junit-platform-commons:1.7.2
     |         +--- org.junit:junit-bom:5.7.2 (*)
     |         \--- org.apiguardian:apiguardian-api:1.1.0
     +--- org.junit.platform:junit-platform-testkit -> 1.7.2
     |    +--- org.junit:junit-bom:5.7.2 (*)
     |    +--- org.apiguardian:apiguardian-api:1.1.0
     |    +--- org.assertj:assertj-core:3.16.1
     |    +--- org.opentest4j:opentest4j:1.2.0
     |    \--- org.junit.platform:junit-platform-launcher:1.7.2
     |         +--- org.junit:junit-bom:5.7.2 (*)
     |         +--- org.apiguardian:apiguardian-api:1.1.0
     |         \--- org.junit.platform:junit-platform-engine:1.7.2 (*)
     +--- org.hamcrest:hamcrest:2.2
     +--- org.jetbrains:annotations:20.1.0
     +--- org.ow2.asm:asm:9.1
     +--- net.bytebuddy:byte-buddy:1.11.0
     +--- cglib:cglib-nodep:3.3.0
     \--- org.objenesis:objenesis:3.2
...
----

We can see the Gradle 5.1 API dependencies for the `compileClasspath`, and the absence of the API dependencies for `testRuntimeClasspath` as expected.

For more information, see Gradle Plugin Development <<../../manual/plugin-references.adoc#sec:plugin-reference-gradledev,reference chapters>> and <<../../manual/gradle-plugin-development.adoc#,user manual chapter>>.
