= {C Application} Custom Source Layout Globing
:summary: Set custom source layout Globing for a {C application}.
:type: sample-chapter
:tags: sample, {application}, sources, native, {C}, gradle
:category: {C}
:description: See how to set the source layout globing of {an application} implemented in {C} using the Gradle Nokee plugins.

NOTE: You can open this sample inside an IDE using the https://www.jetbrains.com/help/idea/gradle.html#gradle_import_project_start[IntelliJ native importer] or https://projects.eclipse.org/projects/tools.buildship[Eclipse Buildship].

Here is a sample where we set the source layout globing of {an application} implemented in {C} with no dependencies and minimal configuration.

[source,groovy]
----
plugins {
	id 'dev.nokee.c-application'    // <1>
}

application {
    cSources.setFrom(fileTree('srcs') { include '**/*.c' })// <2>
}

----
<1> Apply the <<plugin:c-application, C application plugin>>.
<2> Set C sources to *include* all files with c extension recursively from the `srcs` directory.


NOTE: More filter patterns exist such as *exclude*, *matching*, etc.
Refer to the Gradle documentation for more information.

Demonstration below where we see the application builds and runs:

[source,terminal]
----
$ ./gradlew assemble

BUILD SUCCESSFUL
4 actionable tasks: 4 executed
----

Demonstration when including a file that doesn't meet the source filters:

[source,terminal]
----
$ echo "broken!" > srcs/a_broken.potato           // <1>
$ ./gradlew clean assemble                      // <2>

BUILD SUCCESSFUL                                // <3>
4 actionable tasks: 4 executed
----
<1> Create a broken C source file in conventional location with no C extension.
<2> Rebuilding C application using task `clean`
<3> The result ignores the incorrect *.potato* source file and succeed.




