= Application with JNI Library
:jbake-summary: Use a JNI Library in an application.
:jbake-type: sample_chapter
:jbake-category: Java Native Interface (JNI)
:jbake-description: See how to use a Java Native Interface (JNI) library within an application using Gradle Nokee plugins.

NOTE: You can open this sample inside an IDE using the https://www.jetbrains.com/help/idea/gradle.html#gradle_import_project_start[IntelliJ native importer] or https://projects.eclipse.org/projects/tools.buildship[Eclipse Buildship].

This sample shows how a JVM application in Gradle can use a JNI library.
The library has no dependencies, and the build has a minimal configuration.

In this sample, we are using a JNI library implemented in Java and {cpp} within an application implemented in Java; however, this applies to other JVM and native languages as well.

====
[.multi-language-sample]
=====
.build.gradle
[source,groovy]
----
include::{includedir}/groovy-dsl/build.gradle[]
----
=====
[.multi-language-sample]
=====
.build.gradle.kts
[source,kotlin]
----
include::{includedir}/kotlin-dsl/build.gradle.kts[]
----
=====
====

To build the library:

[listing.terminal]
----
$ ./gradlew run

> Task :run
Bonjour, World!

BUILD SUCCESSFUL
6 actionable tasks: 6 executed
----

It's also possible to build a distribution archive:

[listing.terminal]
----
$ ./gradlew :distZip

BUILD SUCCESSFUL
8 actionable tasks: 3 executed, 5 up-to-date
$ ls ./build/distributions/*.zip
./build/distributions/jvm-application-with-jni-library.zip
----

It is possible to use the distribution on a system where the code wasn't built, given the native component of the JNI library is supported on the platform:

[listing.terminal]
----
$ mv ./build/distributions/jvm-application-with-jni-library.zip .
$ ./gradlew clean

BUILD SUCCESSFUL
2 actionable tasks: 2 executed
$ unzip jvm-application-with-jni-library.zip -d .
Archive:  /Users/daniel/jvm-application-with-jni-library.zip
   creating: /Users/daniel/jvm-application-with-jni-library/
   creating: /Users/daniel/jvm-application-with-jni-library/lib/
  inflating: /Users/daniel/jvm-application-with-jni-library/lib/jvm-application-with-jni-library.jar
  inflating: /Users/daniel/jvm-application-with-jni-library/lib/jni-library.jar
   creating: /Users/daniel/jvm-application-with-jni-library/bin/
  inflating: /Users/daniel/jvm-application-with-jni-library/bin/jvm-application-with-jni-library
  inflating: /Users/daniel/jvm-application-with-jni-library/bin/jvm-application-with-jni-library.bat
$ ./jvm-application-with-jni-library/bin/jvm-application-with-jni-library
Bonjour, World!
----

For more information, see <<../../manual/jni-library-plugin.adoc#,JNI Library Plugin>>, <<../../manual/cpp-language-plugin.adoc#,{cpp} Language Plugin>> and link:{gradle-user-manual}/application_plugin.html[Application Plugin] reference chapters.
