description: Run Gradle with Nokee cache
name: Gradle
inputs:
    arguments:
        description: 'Gradle arguments'
        required: true
    build-cache-username:
        description: 'Build cache username'
        required: true
    build-cache-password:
        description: 'Build cache password'
        required: true
    github-token:
        description: 'GitHub token'
        required: true
    build-scan-access-key:
        description: 'Build cache access key'
        required: true
runs:
    using: composite
    steps:
        -   uses: actions/setup-java@v3
            with:
                distribution: temurin
                java-version: 8
        -   uses: gradle/gradle-build-action@v2
            with:
                arguments: ${{ inputs.arguments }} --no-daemon --continue "-Dgradle.enterprise.url=https://ge.nokee.dev/" "-Dgradle.cache.remote.username=${{ inputs.build-cache-username }}" "-Dgradle.cache.remote.password=${{ inputs.build-cache-password }}" "-Dgradle.cache.remote.push=true"
                gradle-version: wrapper
            env:
                GRADLE_ENTERPRISE_ACCESS_KEY: ${{ inputs.build-scan-access-key }}
