description: Run Gradle with Nokee cache
name: Gradle
inputs:
    arguments:
        description: 'Gradle arguments'
        required: true
    build-cache-username:
        description: 'Build cache username'
        required: true
    build-cache-password:
        description: 'Build cache password'
        required: true
    github-token:
        description: 'GitHub token'
        required: true
runs:
    using: composite
    steps:
        -   uses: actions/setup-java@v2
            with:
                distribution: temurin
                java-version: 8
        -   uses: gradle/gradle-build-action@v2
            id: gradle
            with:
                arguments: ${{ inputs.arguments }} --no-daemon --continue --scan "-DnokeeBuildCacheUsername=${{ inputs.build-cache-username }}" "-DnokeeBuildCachePassword=${{ inputs.build-cache-password }}"
                gradle-version: wrapper
        - name: "Tag build scan url"
          uses: actions/github-script@v5
          if: failure()
          with:
              github-token: ${{ inputs.github-token }}
              script: |
                  github.rest.repos.createCommitStatus({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    sha: ${{ github.sha }},
                    state: ${{ steps.gradle.outcome }},
                    target_url: ${{ steps.gradle.outputs.build-scan-url }},
                    context: '❌ ${{ github.workflow }} / ${{ github.job_id }}'
                  })
