description: Run Gradle with Nokee cache
name: Gradle
inputs:
    arguments:
        description: 'Gradle arguments'
        required: true
    build-cache-username:
        description: 'Build cache username'
        required: true
    build-cache-password:
        description: 'Build cache password'
        required: true
runs:
    using: composite
    steps:
        -   uses: actions/setup-java@v2
            with:
                java-version: 8
        -   uses: gradle/gradle-build-action@v2
            with:
                arguments: ${{ inputs.arguments }} --continue "-DnokeeBuildCacheUsername=${{ inputs.build-cache-username }}" "-DnokeeBuildCachePassword=${{ inputs.build-cache-password }}"
                gradle-version: wrapper
