[[plugin:nokee-version-management]]
= Nokee Version Management
:jbake-status: published
:jbake-type: reference_chapter
:jbake-tags: user manual, gradle plugin reference, version management, gradle
:jbake-description: Learn what the Nokee version management plugin (i.e. dev.nokee.nokee-version-management) has to offer for your Gradle build.

The Nokee Version Management Plugin provides the repository and resolution strategy for Nokee plugins in a Gradle build.

[[sec:nokee-version-management-usage]]
== Usage

.Applying the Nokee Version Management Plugin
====
[.multi-language-sample]
=====
.settings.gradle
[source,groovy]
----
plugins {
   id 'dev.nokee.nokee-version-management'
}
----
=====
[.multi-language-sample]
=====
.settings.gradle.kts
[source,kotlin]
----
plugins {
   id("dev.nokee.nokee-version-management")
}
----
=====
====

== Plugin Management

=== Repositories

Registers a Maven repository to resolve the Nokee plugins matching the specified version.
Based on the Nokee version used, https://repo.nokee.dev/release (or https://repo.nokee.dev/snapshot).
Only Nokee artifacts are resolvable from this repository.
The URL are overridable via System properties `dev.nokee.repository.release.url.override` or `dev.nokee.repository.snapshot.url.override`.

The plugin will keep the implicit declaration of `gradlePluginPortal()` when adding its own repository.
You can disable the behaviour via System property `dev.nokee.repository.gradlePluginPortal` by using the `disabled` value.
Keep in mind that Nokee plugins has dependencies on remote artifacts from `mavenCentral()` which are mirrored to `gradlePluginPortal()`.

=== Version Alignment

Upon resolution, all plugins in the namespace `dev.nokee` resolve to the specified version.

== Choosing the Nokee Version

The plugin determine which Nokee version to use by reading it from the following sources, in this order:

1. The `NOKEE_VERSION` environment variable, if specified.
2. The first Nokee version found by searching each of its parent build until reaching the root build (e.g. `gradle.parent` is null).
3. The `.nokee-version` file in the Gradle project root (e.g. `settingsDir`/`rootDir`).

== Seeding Nokee Version

When no version is found, we seed a Nokee version in a new `.nokee-version` according to the following order:

1. If networking activity is allowed, the current release version from https://services.nokee.dev/versions/current.json
2. The current release version known at the time of plugin was released.

== System properties

[[sysProp:dev.nokee.repository.release.url.override]]
`dev.nokee.repository.release.url.override` (any URL string)::
Overrides the repository URL for release version.

[[sysProp:dev.nokee.repository.snapshot.url.override]]
`dev.nokee.repository.snapshot.url.override` (any URL string)::
Overrides the repository URL for snapshot version.

[[sysProp:dev.nokee.repository.gradlePluginPortal]]
`dev.nokee.repository.gradlePluginPortal` (implicit|enabled|disabled)::
Gradle Plugin Portal repository behaviour.
Disabled will not include the repository.
Users will have to declare it if they want it.
Enabled will always declare the repository.
Implicit (default) will declare it only if no repository were previously added.

== Environment Variables

[[envVar:NOKEE_VERSION]]
`NOKEE_VERSION`::
Overrides the Nokee version in use.
