:language: c
:entry-point: application

:plugin-name: {language}-{entry-point}

ifeval::["{plugin-name}" == "c-application"]
:c-application: C application
:an-application: an application
:c: C
:source-file-extension: c
:header-file-extension: h
:application: application
endif::[]

ifeval::["{plugin-name}" == "cpp-application"]
:c-application: {cpp} application
:an-application: an application
:c: {cpp}
:source-file-extension: cpp
:header-file-extension: hpp
:application: application
endif::[]

ifeval::["{plugin-name}" == "objective-c-application"]
:c-application: Objective-C application
:an-application: an application
:c: Objective-C
:source-file-extension: m
:header-file-extension: h
:application: application
endif::[]

ifeval::["{plugin-name}" == "objective-cpp-application"]
:c-application: Objective-{cpp} application
:an-application: an application
:c: Objective-{cpp}
:source-file-extension: mm
:header-file-extension: hpp
:application: application
endif::[]

ifeval::["{plugin-name}" == "swift-application"]
:c-application: Swift application
:an-application: an application
:c: Swift
:source-file-extension: swift
:application: application
endif::[]

ifeval::["{plugin-name}" == "c-library"]
:c-application: C library
:an-application: a library
:c: C
:source-file-extension: c
:header-file-extension: h
:application: library
endif::[]

ifeval::["{plugin-name}" == "cpp-library"]
:c-application: {cpp} library
:an-application: a library
:c: {cpp}
:source-file-extension: cpp
:header-file-extension: hpp
:application: library
endif::[]

ifeval::["{plugin-name}" == "objective-c-library"]
:c-application: Objective-C library
:an-application: a library
:c: Objective-C
:source-file-extension: m
:header-file-extension: h
:application: library
endif::[]

ifeval::["{plugin-name}" == "objective-cpp-library"]
:c-application: Objective-{cpp} library
:an-application: a library
:c: Objective-{cpp}
:source-file-extension: mm
:header-file-extension: hpp
:application: library
endif::[]

ifeval::["{plugin-name}" == "swift-library"]
:c-application: Swift library
:an-application: a library
:c: Swift
:source-file-extension: swift
:application: library
endif::[]

:ref-plugin: <<plugin:{plugin-name}, {c-application} plugin>>

ifndef::c[ERROR: Please define `plugin-name` attribute.]

= {c-application} Custom Source File mixing source layout (appending)
:summary: Set custom source file mixing source layout for a {c-application}.
:type: sample-chapter
:tags: sample, {application}, sources, native, {C}, gradle
:category: {C}
:description: See how to set the source file mixing source layout of {an application} implemented in {C} using the Gradle Nokee plugins.

NOTE: You can open this sample inside an IDE using the https://www.jetbrains.com/help/idea/gradle.html#gradle_import_project_start[IntelliJ native importer] or https://projects.eclipse.org/projects/tools.buildship[Eclipse Buildship].

Here is a sample where we set the custom source file by _mixing source layout_ also called _appending_ {an-application} implemented in {C} with no dependencies and minimal configuration.

[source,groovy]
----
plugins {
	id 'dev.nokee.c-application'    // <1>
}

application {
//  cSources.from('src/main/c') // default initially set by convention <2>
    cSources.from('sources/application.c') // <3>
    cSources.from('sources/greeter.c') // <4>
}

----
<1> Apply the {ref-plugin}.
<2> Set {C} sources under `main.c.` This section is commented to show it is set by convention and doesn't need to be implemented.
<3> Set {C} sources under `application.c`
<4> Set {C} sources under `greeter.c` that will append to previous command (3)

NOTE:  _from_ can take any type of source layout (globing, cherry-picking, generated).

As per below example, creating a broken source file at the conventional location will fail the build since
the full sources include everything under *src/main/c*; *sources/application.c* ; *sources/greeter.c*



The {application} build fails:


[source,terminal]
----
$ mkdir -p src/main/c
$ echo "broken!" > src/main/c/broken.c
$ ./gradlew clean assemble

BUILD FAIL

----

