= {C Application} Custom Source File mixing source layout (appending)
:summary: Set custom source file mixing source layout for a {C application}.
:type: sample-chapter
:tags: sample, {application}, sources, native, {C}, gradle
:category: {C}
:description: See how to set the source file mixing source layout of {an application} implemented in {C} using the Gradle Nokee plugins.

NOTE: You can open this sample inside an IDE using the https://www.jetbrains.com/help/idea/gradle.html#gradle_import_project_start[IntelliJ native importer] or https://projects.eclipse.org/projects/tools.buildship[Eclipse Buildship].

Here is a sample where we set the source file mixing source layout also called appending {an application} implemented in {C} with no dependencies and minimal configuration.

[source,groovy]
----
plugins {
	id 'dev.nokee.c-application'    // <1>
}

application {
//  cSources.from('src/main/c') // this is by default initially set by convention
    cSources.from('sources/application.c') // <2>
    cSources.from('sources/greeter.c') // <3>
}

----
<1> Apply the <<plugin:c-application, C application plugin>>.
<2> Set C sources under main.c
<3> Set C sources greeter.c that will append to previous command (2)

NOTE:  that from can take any type of source layout (globing, cherry-picking, generated).

As per below example,creating a broken source file at a conventional location will fail the build since
the full sources are: everything under *src/main/c*; *sources/application.c* ; *sources/greeter.c*
//TODO reword and reword comment block explanation


The application build fails:


[source,terminal]
----
$ mkdir -p src/main/c
$ echo "broken!" > src/main/c/broken.c
$ ./gradlew clean assemble

BUILD FAIL

----

