package dev.nokee.platform.nativebase.internal.dependencies;

import dev.nokee.platform.base.internal.dependencies.ComponentDependenciesContainer;
import dev.nokee.platform.nativebase.NativeApplicationComponentDependencies;

public interface NativeApplicationComponentDependenciesInternal extends NativeApplicationComponentDependencies, ComponentDependenciesContainer {
}
