name: Contributor

on: push

jobs:
    assemble-without-secrets:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-java@v2
                with:
                    distribution: temurin
                    java-version: 8
            -   name: Build all code
                id: gradle
                uses: gradle/gradle-build-action@v2
                with:
                    arguments: :platformJni:assemble --scan --continue --no-daemon
